### ISSUE TITLE
when i excute "fairseq_cli/hydra_train.py \" have prompt missing import.

### ISSUE THREAD

**Issue by guobabaya** [Hertin/WavPrompt#1]
(base) [pengtl@vm-07 wavprompt]$ ./run.sh --stage 10 --stop-stage 10   --manifest-path "$(pwd)/manifest/librispeech100" --config-name "asr_pretraining"   --n-token ${n_token} --reduction-factor ${rf} --freeze_finetune_updates ${freeze_finetune_updates}   --save-Dir $(pwd)/outputs/wavpromptlsp100rf${rf}ntok${n_token}
Stage 10: Training Fairseq Model (/home/pengtl/WavPrompt-main/wavprompt/manifest/librispeech100) (asr_pretraining)
Params: freeze_finetune_updates: 0 reduction_factor: 8 n_token: 0
Traceback (most recent call last):
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq_cli/hydra_train.py", line 15, in <module>
    from fairseq import distributed_utils, metrics
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/__init__.py", line 33, in <module>
    import fairseq.criterions  # noqa
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/criterions/ctc.py", line 18, in <module>
    from fairseq.data.data_utils import post_process
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/data/__init__.py", line 132, in <module>
    from .audio.file_audio_label_dataset import FileAudioLabelDataset
ModuleNotFoundError: No module named 'fairseq.data.audio.file_audio_label_dataset'

**Comment by Hertin** [comment]
I realized I incorrectly configured my gitignore file, resulting some of the files not being committed. I just fixed it. Could you try it again?

**Comment by guobabaya** [comment]
> 我意识到我错误地配置了我的 gitignore 文件，导致一些文件没有被提交。我刚刚修好了。你能再试一次吗？

Thank you for your reply,i will try it again.

**Comment by guobabaya** [comment]
> I realized I incorrectly configured my gitignore file, resulting some of the files not being committed. I just fixed it. Could you try it again?

Thank you for your reply,i will try it again.

**Comment by guobabaya** [comment]
> I realized I incorrectly configured my gitignore file, resulting some of the files not being committed. I just fixed it. Could you try it again?
When I pull data again, the problem still exists. Is it because my fairseq is not a backward version? Because my ECS can't use the GIT command, I didn't reset my fairseq. I don't know the reason of this problem.Can you give me some advice.

**Comment by Hertin** [comment]
Did you run the setup.sh script again? In stage 2 it copies the files in wavprompt/fairseq to fairseq/fairseq so that the fairseq would have the FileAudioLabelDataset class

**Comment by guobabaya** [comment]
> Did you run the setup.sh script stage 2 again? In stage 2 it copies the files in wavprompt/fairseq to fairseq/fairseq so that the fairseq would have the FileAudioLabelDataset class

yes,i have run the setup.sh and file_audio_label_dataset.py already exist in /home/pengtl/WavPrompt/fairseq/fairseq/data/audio/ ,this is really a trouble.

**Comment by guobabaya** [comment]
> Did you run the setup.sh script stage 2 again? In stage 2 it copies the files in wavprompt/fairseq to fairseq/fairseq so that the fairseq would have the FileAudioLabelDataset class

hi，bro! I finally solved this problem. The problem is that I didn't adjust my CONDA environment after I resetup. Your re upload was useful before. Thank you sincerely!
